# Generated by Django 4.0.5 on 2022-08-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='foto_equipamento',
            field=models.ImageField(default=0, upload_to='photos_cpu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu',
            name='tombo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
