# Generated by Django 4.0.5 on 2022-08-31 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0002_cpu_foto_equipamento_alter_cpu_tombo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='placa_de_video',
        ),
        migrations.AlterField(
            model_name='cpu',
            name='data_edicao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Edição'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='foto_equipamento',
            field=models.ImageField(help_text='Faça aqui o upload das fotos do equipamento.', upload_to='photos_cpu', verbose_name='Foto do Equipamento'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='hd',
            field=models.CharField(choices=[('SEM HD', 'SEM HD'), ('120GB', '120GB'), ('160GB', '160GB'), ('250GB', '250GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('1TB', '1TB')], max_length=100, verbose_name='HD'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='hostname',
            field=models.CharField(help_text='Ex: WS-HP-GEAI-6541', max_length=100),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='leitor_cd',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=5, verbose_name='Leitor de CD'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='memoria_ram',
            field=models.CharField(choices=[('DDR2 - 2GB', 'DDR2 - 2GB'), ('DDR2 - 3GB', 'DDR2 - 3GB'), ('DDR2 - 4GB', 'DDR2 - 4GB'), ('DDR3 - 2GB', 'DDR3 - 2GB'), ('DDR3 - 4GB', 'DDR3 - 4GB'), ('DDR3 - 6GB', 'DDR3 - 6GB'), ('DDR3 - 8GB', 'DDR3 - 8GB'), ('DDR3 - 16GB', 'DDR3 - 16GB'), ('DDR4 - 8GB', 'DDR4 - 8GB'), ('DDR4 - 16GB', 'DDR4 - 16GB')], max_length=100, verbose_name='Memória Ram'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='numero_serie',
            field=models.CharField(help_text='Ex:BRJ4030HPS', max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='sistema_operacional',
            field=models.CharField(choices=[('WINDOWS 7', 'WINDOWS 7'), ('WINDOWS 10', 'WINDOWS 10'), ('WINDOWS 11', 'WINDOWS 11')], max_length=100, verbose_name='Sistema Operacional'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ssd',
            field=models.CharField(choices=[('SEM SSD', 'SEM SSD'), ('120GB', '120GB'), ('240GB', '240GB'), ('480GB', '480GB')], max_length=100, verbose_name='SSD'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='tombo',
            field=models.IntegerField(help_text='Ex: 6541', primary_key=True, serialize=False, verbose_name='Tombo'),
        ),
    ]
