# Generated by Django 4.0.5 on 2022-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0003_remove_cpu_placa_de_video_alter_cpu_data_edicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='ip',
            field=models.CharField(default=0, help_text='Ex: 10.10.0.3', max_length=20, verbose_name='Endereço IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='mac',
            field=models.CharField(default=0, help_text='Ex: ', max_length=20, verbose_name='Endereço MAC'),
            preserve_default=False,
        ),
    ]
