# Generated by Django 4.0.5 on 2022-09-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_cpu_ip_cpu_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='placa_de_video',
            field=models.CharField(choices=[('SEM VIDEO OFFBOARD', 'SEM VIDEO OFFBOARD'), ('INTEL IRIS XE', 'INTEL IRIS XE'), ('GEFORCE 7200GS', 'GEFORCE 7200GS'), ('GEFORCE 7300SE', 'GEFORCE 7300SE'), ('GEFORCE 8400GS', 'GEFORCE 8400GS'), ('GEFORCE GT210', 'GEFORCE GT210'), ('GEFORCE GT710', 'GEFORCE GT710'), ('GEFORCE GT730', 'GEFORCE GT730'), ('NVIDIA GTX1050Ti', 'NVIDIA GTX1050Ti'), ('NVIDIA GTX1660', 'NVIDIA GTX1660'), ('NVIDIA GTX1660SUPER', 'NVIDIA GTX1660SUPER'), ('NVIDIA GTX1660Ti', 'NVIDIA GTX1660Ti'), ('NVIDIA QUADRO 2000', 'NVIDIA QUADRO 2000'), ('NVIDIA QUADRO K620', 'NVIDIA QUADRO K620'), ('NVIDIA RTX3050', 'NVIDIA RTX3050'), ('NVIDIA RTX3060', 'NVIDIA RTX3060'), ('RADEON 3000', 'RADEON 3000'), ('RADEON HD5450', 'RADEON HD5450'), ('RADEON HD7560D', 'RADEON HD7560D')], default=0, max_length=100, verbose_name='Placa de Vídeo'),
            preserve_default=False,
        ),
    ]
