# Generated by Django 4.0.5 on 2022-08-31 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('tombo', models.IntegerField(help_text='Ex: 6541', primary_key=True, serialize=False, verbose_name='Tombo')),
                ('numero_serie', models.CharField(help_text='Ex:BRJ4030HPS', max_length=100, verbose_name='Número de Série')),
                ('marca', models.CharField(choices=[('ACER', 'ACER'), ('AOC', 'AOC'), ('DELL', 'DELL'), ('HP', 'HP'), ('LENOVO', 'LENOVO'), ('LG', 'LG'), ('PCTOP', 'PCTOP'), ('POSITIVO', 'POSITIVO'), ('PROVIEW', 'PROVIEW'), ('SAMSUNG', 'SAMSUNG')], max_length=100)),
                ('foto_equipamento', models.ImageField(help_text='Faça aqui o upload das fotos do equipamento.', upload_to='photos_cpu', verbose_name='Foto do Equipamento')),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Edição')),
            ],
        ),
    ]
