# Generated by Django 4.0.5 on 2022-08-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='foto_equipamento',
            field=models.ImageField(blank=True, help_text='Faça aqui o upload das fotos do equipamento.', upload_to='photos_cpu', verbose_name='Foto do Equipamento'),
        ),
    ]
