# Generated by Django 4.0.5 on 2022-08-31 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nobreak',
            fields=[
                ('tombo', models.IntegerField(help_text='Ex: 6541', primary_key=True, serialize=False, verbose_name='Tombo')),
                ('marca', models.CharField(choices=[('INTELBRAS', 'INTELBRAS'), ('RAGTECH', 'RAGTECH'), ('SIDEWAY', 'SIDEWAY'), ('SMS', 'SMS'), ('STAYTION', 'STAYTION'), ('TS SHARA', 'TS SHARA')], max_length=100)),
                ('foto_equipamento', models.ImageField(blank=True, help_text='Faça aqui o upload das fotos do equipamento.', upload_to='photos_cpu', verbose_name='Foto do Equipamento')),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Edição')),
            ],
        ),
    ]
