# Generated by Django 4.0.5 on 2022-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('usuario_ad', models.CharField(max_length=50, verbose_name='Usuário AD')),
                ('setor', models.CharField(max_length=120, verbose_name='Setor')),
                ('tombo_cpu', models.IntegerField(max_length=10)),
                ('tombo_monitor_1', models.IntegerField(max_length=10)),
                ('tombo_monitor_2', models.IntegerField(blank=True, max_length=10)),
                ('tombo_nobreak', models.IntegerField(max_length=10)),
            ],
        ),
    ]
