# Generated by Django 4.0.5 on 2022-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='tombo_cpu',
            field=models.IntegerField(verbose_name='Tombo CPU'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='tombo_monitor_1',
            field=models.IntegerField(verbose_name='Tombo Monitor 1'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='tombo_monitor_2',
            field=models.IntegerField(blank=True, verbose_name='Tombo Monitor 2'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='tombo_nobreak',
            field=models.IntegerField(verbose_name='Tombo Nobreak'),
        ),
    ]
