# Generated by Django 4.0.5 on 2022-09-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitore', '0002_alter_monitor_foto_equipamento'),
        ('controle', '0003_alter_controle_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='tombo_monitor_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle', to='monitore.monitor'),
        ),
    ]
