# Generated by Django 4.0.5 on 2022-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_alter_controle_tombo_monitor_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='tombo_monitor_2',
            field=models.IntegerField(null=True, verbose_name='Tombo Monitor 2'),
        ),
    ]
