# Generated by Django 4.0.5 on 2022-09-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_cpu_ip_cpu_mac'),
        ('controle', '0006_alter_controle_tombo_monitor_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='tombo_cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle', to='cpu.cpu'),
        ),
    ]
