# Generated by Django 4.0.5 on 2022-09-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_cpu_ip_cpu_mac'),
        ('monitore', '0002_alter_monitor_foto_equipamento'),
        ('nobreak', '0001_initial'),
        ('controle', '0007_alter_controle_tombo_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='tombo_cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_cpu', to='cpu.cpu'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='tombo_monitor_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_monitor_1', to='monitore.monitor'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='tombo_monitor_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_monitor_2', to='monitore.monitor'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='tombo_nobreak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_nobreak', to='nobreak.nobreak'),
        ),
    ]
