# Generated by Django 4.1.7 on 2023-08-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controle", "0011_alter_controle_tombo_monitor_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controle",
            name="setor",
            field=models.CharField(
                choices=[
                    ("AP - AGENTES DE PORTARIA", "AP - AGENTES DE PORTARIA"),
                    ("BSEC - BIBLIOTECA SECUNDÁRIA", "BSEC - BIBLIOTECA SECUNDÁRIA"),
                    (
                        "CGP - CENTRAL DE GESTÃO DE PROJETOS",
                        "CGP - CENTRAL DE GESTÃO DE PROJETOS",
                    ),
                    (
                        "DMKT - DEPARTAMENTO DE MARKETING",
                        "DMKT - DEPARTAMENTO DE MARKETING",
                    ),
                    ("EQSUP - EQUIPE DE SUPORTE", "EQSUP - EQUIPE DE SUPORTE"),
                    ("FIN - FINANÇAS", "FIN - FINANÇAS"),
                    (
                        "GRH - GESTÃO DE RECURSOS HUMANOS",
                        "GRH - GESTÃO DE RECURSOS HUMANOS",
                    ),
                    (
                        "GSTR - GERENCIA DE SERVICO DE TRANSPORTE",
                        "GSTR - GERENCIA DE SERVICO DE TRANSPORTE",
                    ),
                    (
                        "IPTI - INSTITUTO DE PESQUISA TECNOLÓGICA E INDUSTRIAL",
                        "IPTI - INSTITUTO DE PESQUISA TECNOLÓGICA E INDUSTRIAL",
                    ),
                    (
                        "LCP - LABORATÓRIO DE CONTROLE DE PROCESSOS",
                        "LCP - LABORATÓRIO DE CONTROLE DE PROCESSOS",
                    ),
                    ("MCOM - COMUNICAÇÃO E MÍDIA", "MCOM - COMUNICAÇÃO E MÍDIA"),
                    ("OP - OPERAÇÕES", "OP - OPERAÇÕES"),
                    ("PLG - PLANEJAMENTO E GESTÃO", "PLG - PLANEJAMENTO E GESTÃO"),
                    ("RH - RECURSOS HUMANOS", "RH - RECURSOS HUMANOS"),
                    (
                        "SDTI - SUPORTE E DESENVOLVIMENTO DE TECNOLOGIAS DA INFORMAÇÃO",
                        "SDTI - SUPORTE E DESENVOLVIMENTO DE TECNOLOGIAS DA INFORMAÇÃO",
                    ),
                    ("VND - VENDAS", "VND - VENDAS"),
                    ("UNIDADE DE CONTROLE", "UNIDADE DE CONTROLE"),
                ],
                max_length=120,
                verbose_name="Setor",
            ),
        ),
    ]
